baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'gochowdown'
defaultContentLanguage = "de"
[[menu.main]]
name = "Home"
weight = 1
url = "/"

[[menu.main]]
name = "Category"
weight = 2
url = "/category/"

[[menu.main]]
name = "Cuisine"
weight = 3
url = "/cuisine/"

[[menu.main]]
name = "Tags"
weight = 4
url = "/tags/"
