baseURL = 'https://d3ns0n.github.io/recipes/'
languageCode = 'en-us'
title = 'Unsere beliebtesten Rezepte'
theme = 'gochowdown'
defaultContentLanguage = "de"
[[menu.main]]
name = "Home"
weight = 1
url = "/"

[[menu.main]]
name = "Category"
weight = 2
url = "/categories/"

[[menu.main]]
name = "Cuisine"
weight = 3
url = "/cuisine/"

[[menu.main]]
name = "Tags"
weight = 4
url = "/tags/"
